# Generated by Django 2.2.16 on 2022-07-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220727_1902'),
        ('users', '0002_auto_20220728_1701'),
    ]

    operations = [
    ]
