# Generated by Django 2.2.16 on 2022-08-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220801_1841'),
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
    ]
