# Generated by Django 2.2.16 on 2022-08-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220801_2249'),
        ('users', '0004_auto_20220802_0809'),
    ]

    operations = [
    ]
