# Generated by Django 2.2.16 on 2022-08-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_review'),
        ('reviews', '0002_auto_20220801_0819'),
    ]

    operations = [
    ]
